apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.label }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.label }}
  template:
    metadata:
      labels:
        app: {{ .Values.label }}
    spec:
      containers:
      - name: nginx
        image: nginx:1.16.1
        imagePullPolicy: {{ .Values.imagePolicy }}
        ports:
        - containerPort: 80
        volumeMounts: # consume as volume
          - name: {{ .Values.volume }}
            mountPath: "/usr/share/nginx/html"
            readOnly: true
      volumes:
        - name: {{ .Values.volume }}
          configMap:
            name: {{ .Values.configmap.name }}
